#include "script_component.hpp"

class CfgPatches {
    class ADDON {
        name = QUOTE(COMPONENT);
        units[] = {};
        weapons[] = {};
        requiredVersion = REQUIRED_VERSION;
        requiredAddons[] = {
            "synixe_standardization_main",
        };
        VERSION_CONFIG;
    };
};

#define DISABLE_MODULE(CLASS) \
    class CLASS: Module_F { \
        scope = 1; \
    }

class CfgVehicles {
    class Module_F;
    class ModuleSound_F;
    class ModuleRadio_F: ModuleSound_F {
        scope = 1;
    };
    DISABLE_MODULE(CBA_ModuleAttack);
    DISABLE_MODULE(CBA_ModuleDefend);
    DISABLE_MODULE(CBA_ModulePatrol);
    DISABLE_MODULE(HighCommand);
    DISABLE_MODULE(HighCommandSubordinate);
    DISABLE_MODULE(MartaManager);
    DISABLE_MODULE(ModuleAlchemist_lxWS);
    DISABLE_MODULE(ModuleBleedTickets_F);
    DISABLE_MODULE(ModuleCAS_F);
    DISABLE_MODULE(ModuleChat_F);
    DISABLE_MODULE(ModuleCivilianPresence_F);
    DISABLE_MODULE(ModuleCivilianPresenceSafeSpot_F);
    DISABLE_MODULE(ModuleCivilianPresenceUnit_F);
    DISABLE_MODULE(ModuleCombatGetIn);
    DISABLE_MODULE(ModuleCombatPatrol_Init_F);
    DISABLE_MODULE(ModuleCombatPatrol_LocationAdd_F);
    DISABLE_MODULE(ModuleCombatPatrol_LocationAzimuthBlacklist_F);
    DISABLE_MODULE(ModuleCombatPatrol_LocationMove_F);
    DISABLE_MODULE(ModuleCombatPatrol_LocationRemove_F);
    DISABLE_MODULE(ModuleCountdown_F);
    DISABLE_MODULE(ModuleCreateDiaryRecord_F);
    DISABLE_MODULE(ModuleCuratorUnlockArea_F);
    DISABLE_MODULE(ModuleCuratorUnlockObject_F);
    DISABLE_MODULE(ModuleDate_F);
    DISABLE_MODULE(ModuleEndMission_F);
    DISABLE_MODULE(ModuleFiringDrill_F);
    DISABLE_MODULE(ModuleFlare_F);
    DISABLE_MODULE(ModuleFriendlyFire_F);
    DISABLE_MODULE(ModuleGenericRadio_F);
    DISABLE_MODULE(ModuleGroupID);
    DISABLE_MODULE(ModuleHealth_F);
    DISABLE_MODULE(ModuleHitMarker_RF);
    DISABLE_MODULE(ModuleHQ_F);
    DISABLE_MODULE(ModuleHvtEndGameObjective_F);
    DISABLE_MODULE(ModuleHvtObjectivesInstance_F);
    DISABLE_MODULE(ModuleHvtSimpleObjective_F);
    DISABLE_MODULE(ModuleHvtStartGameObjective_F);
    DISABLE_MODULE(ModuleLiveFeedEffects_F);
    DISABLE_MODULE(ModuleLiveFeedInit_F);
    DISABLE_MODULE(ModuleLiveFeedSetSource_F);
    DISABLE_MODULE(ModuleLiveFeedSetTarget_F);
    DISABLE_MODULE(ModuleLiveFeedTerminate_F);
    DISABLE_MODULE(ModuleMissionName_F);
    DISABLE_MODULE(ModuleMPTypeDefense_F);
    DISABLE_MODULE(ModuleMPTypeGameMaster_F);
    DISABLE_MODULE(ModuleMPTypeGroundSupport_F);
    DISABLE_MODULE(ModuleMPTypeGroundSupportBase_F);
    DISABLE_MODULE(ModuleMPTypeSectorControl_F);
    DISABLE_MODULE(ModuleMPTypeSeize_F);
    DISABLE_MODULE(ModuleObjectiveRaceCP_F);
    DISABLE_MODULE(ModuleObjectiveRaceFinish_F);
    DISABLE_MODULE(ModuleObjectiveRaceStart_F);
    DISABLE_MODULE(ModuleOmQRF_F);
    DISABLE_MODULE(ModuleOrdnance_F);
    DISABLE_MODULE(ModulePoster_F);
    DISABLE_MODULE(ModulePostprocess_F);
    DISABLE_MODULE(ModuleRating_F);
    DISABLE_MODULE(ModuleRespawnPosition_F);
    DISABLE_MODULE(ModuleRespawnTickets_F);
    DISABLE_MODULE(ModuleRespawnVehicle_F);
    DISABLE_MODULE(ModuleSaveGame_F);
    DISABLE_MODULE(ModuleSector_F);
    DISABLE_MODULE(ModuleSectorDummy_F);
    DISABLE_MODULE(ModuleSkiptime_F);
    DISABLE_MODULE(ModuleSkirmishTrigger_F);
    DISABLE_MODULE(ModuleSlingload_F);
    DISABLE_MODULE(ModuleSpawnAI_F);
    DISABLE_MODULE(ModuleSpawnAIOptions_F);
    DISABLE_MODULE(ModuleSpawnAIPoint_F);
    DISABLE_MODULE(ModuleSpawnAISectorTactic_F);
    DISABLE_MODULE(ModuleStrategicMapInit_F);
    DISABLE_MODULE(ModuleStrategicMapMission_F);
    DISABLE_MODULE(ModuleStrategicMapModuleOpen_F);
    DISABLE_MODULE(ModuleStrategicMapORBAT_F);
    DISABLE_MODULE(ModuleTaskCreate_F);
    DISABLE_MODULE(ModuleTaskSetDescription_F);
    DISABLE_MODULE(ModuleTaskSetDestination_F);
    DISABLE_MODULE(ModuleTaskSetState_F);
    DISABLE_MODULE(ModuleTimeMultiplier_F);
    DISABLE_MODULE(ModuleTimeTrial_F);
    DISABLE_MODULE(ModuleTracers_F);
    DISABLE_MODULE(ModuleTrident_F);
    DISABLE_MODULE(ModuleVanguardFob_F);
    DISABLE_MODULE(ModuleVanguardObjective_F);
    DISABLE_MODULE(ModuleVanguardScorePersistence_F);
    DISABLE_MODULE(ModuleVolume_F);
    DISABLE_MODULE(ModuleWeather_F);
    DISABLE_MODULE(ModuleWLBase_F);
    DISABLE_MODULE(ModuleWLInit_F);
    DISABLE_MODULE(ModuleWLResponse_F);
    DISABLE_MODULE(ModuleWLSector_F);
    DISABLE_MODULE(ModuleWLSpawnPoint_F);
    DISABLE_MODULE(ModuleZoneProtection_F);
    DISABLE_MODULE(ModuleZoneRestriction_F);
    DISABLE_MODULE(Site_BLUFOR);
    DISABLE_MODULE(Site_Empty);
    DISABLE_MODULE(Site_Independent);
    DISABLE_MODULE(Site_OPFOR);
    DISABLE_MODULE(Site_Patrol);
    DISABLE_MODULE(SupportProvider_Artillery);
    DISABLE_MODULE(SupportProvider_CAS_Bombing);
    DISABLE_MODULE(SupportProvider_CAS_Heli);
    DISABLE_MODULE(SupportProvider_Drop);
    DISABLE_MODULE(SupportProvider_Transport);
    DISABLE_MODULE(SupportProvider_Virtual_Artillery);
    DISABLE_MODULE(SupportProvider_Virtual_CAS_Bombing);
    DISABLE_MODULE(SupportProvider_Virtual_CAS_Heli);
    DISABLE_MODULE(SupportProvider_Virtual_Drop);
    DISABLE_MODULE(SupportProvider_Virtual_Transport);
    DISABLE_MODULE(SupportRequester);

    // Zeus
    DISABLE_MODULE(ModuleCurator_F);
    DISABLE_MODULE(ModuleCuratorAddAddons_F);
    DISABLE_MODULE(ModuleCuratorAddCameraArea_F);
    DISABLE_MODULE(ModuleCuratorAddEditableObjects);
    DISABLE_MODULE(ModuleCuratorAddEditingArea_F);
    DISABLE_MODULE(ModuleCuratorAddEditingAreaPlayers_F);
    DISABLE_MODULE(ModuleCuratorAddIcon_F);
    DISABLE_MODULE(ModuleCuratorAddPoints_F);
    DISABLE_MODULE(ModuleCuratorSetAttributesGroup_F);
    DISABLE_MODULE(ModuleCuratorSetAttributesMarker_F);
    DISABLE_MODULE(ModuleCuratorSetAttributesObject_F);
    DISABLE_MODULE(ModuleCuratorSetAttributesPlayer_F);
    DISABLE_MODULE(ModuleCuratorSetAttributesWaypoint_F);
    DISABLE_MODULE(ModuleCuratorSetCamera_F);
    DISABLE_MODULE(ModuleCuratorSetCoefs_F);
    DISABLE_MODULE(ModuleCuratorSetCosts_F);
    DISABLE_MODULE(ModuleCuratorSetDefaultCosts_F);
    DISABLE_MODULE(ModuleCuratorSetEditingAreaType_F);
    DISABLE_MODULE(ModuleCuratorSetModuleCosts_F);
    DISABLE_MODULE(ModuleCuratorSetObjectCosts_F);
    DISABLE_MODULE(ModuleCuratorSetSideCosts_F);
    DISABLE_MODULE(ModuleLightning_F);

    // Old Man
    DISABLE_MODULE(ModuleOMAwareness_F);
    DISABLE_MODULE(ModuleOmSectorCheckpoint_F);
    DISABLE_MODULE(ModuleOmQuest_DestroyObject_F);
    DISABLE_MODULE(ModuleOmQuest_DestroyObjects_F);
    DISABLE_MODULE(ModuleOmDepot_F);
    DISABLE_MODULE(ModuleOMEconomy);
    DISABLE_MODULE(ModuleOMFastTravel_F);
    DISABLE_MODULE(ModuleOMFastTravelPos_F);
    DISABLE_MODULE(ModuleOmQuest_HoldAction_F);
    DISABLE_MODULE(ModuleOmInit_F);
    DISABLE_MODULE(ModuleOmInitScript_F);
    DISABLE_MODULE(ModuleOMSyndikatAgent);
    DISABLE_MODULE(ModuleOMSyndikatCampPos);
    DISABLE_MODULE(ModuleOmIntel_F);
    DISABLE_MODULE(ModuleOMSyndikatTeam);
    DISABLE_MODULE(ModuleOmMosquitos_F);
    DISABLE_MODULE(ModuleOmMarket_F);
    DISABLE_MODULE(ModuleOmNight_F);
    DISABLE_MODULE(ModulePatrolArea_F);
    DISABLE_MODULE(ModuleOmProtectedVehicle_F);
    DISABLE_MODULE(ModuleOmQRF_F_First);
    DISABLE_MODULE(ModuleOmQRF_F_Second);
    DISABLE_MODULE(ModuleOmQRF_F_Third);
    DISABLE_MODULE(ModuleOmQuest_Defend_F);
    DISABLE_MODULE(ModuleOmQuest_Get_F);
    DISABLE_MODULE(ModuleOmQuest_DeliverPoint_F);
    DISABLE_MODULE(ModuleOmQuest_HostageRescue_F);
    DISABLE_MODULE(ModuleOmQuest_Location_F);
    DISABLE_MODULE(ModuleOmQuest_Support_StartingPos_F);
    DISABLE_MODULE(ModuleOmQuest_Support_F);
    DISABLE_MODULE(ModuleOmQuest_Transport_F);
    DISABLE_MODULE(ModuleOmQuest_TransportPerson_F);
    DISABLE_MODULE(ModuleOMRadio_F);
    DISABLE_MODULE(ModuleOmRandomConversation_F);
    DISABLE_MODULE(ModuleOmRelationship_F);
    DISABLE_MODULE(ModuleOMReputation_F);
    DISABLE_MODULE(ModuleOmRestPoint_F);
    DISABLE_MODULE(ModuleOmSector_F);
    DISABLE_MODULE(ModuleOmRestrictedArea_F);
    DISABLE_MODULE(ModuleOMSmartMarkers_F);
    DISABLE_MODULE(ModuleOmQuest_SupportUnits_F);
    DISABLE_MODULE(ModuleOmActionQueue_F);
    DISABLE_MODULE(ModuleOmTracked_F);
};
